name: Build Env

on:
  push:
    branches: [ "main" ] # コードを上げたら自動でビルド確認

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: |
          docker build -t v_app .
          echo "環境構築完了"
